### ISSUE TITLE
How to train the model?

### ISSUE THREAD

**Issue by caigen001** [pritamqu/ppg2ecg-cardiogan#2]
Hello, could you tell me how to train the model using my data?

**Comment by pritamqu** [comment]
@caigen001 thanks for your interest. you can see our paper [https://arxiv.org/pdf/2010.00104.pdf](https://arxiv.org/pdf/2010.00104.pdf) for a detailed description. Hope this helps.

**Comment by andre1906** [comment]
Would it be possible to make the training code available? I'm having trouble training the generator
